spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${aws-aurora-endpoint}
    username: ${aws-aurora-username}
    password: ${aws-aurora-password}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
      generate-ddl: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
  application:
    name: so1s-api-server

  servlet:
    multipart:
      max-file-size: 100GB
      max-request-size: 100GB


logging:
  level:
    org:
      springframework:
        web:
          filter: DEBUG
      hibernate:
        SQL=DEBUG:

jwt:
  header: Authorization
  # HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  secret: ${jwt-secret}
  token-validity-in-seconds: 86400

cloud:
  aws:
    credentials:
      instance-profile: true
      access-key: ${aws-s3-access-key}
      secret-key: ${aws-s3-secret-key}
    s3:
      bucket: ${aws-s3-bucket}
    region:
      static: ${aws-region}
    stack:
      auto: false

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    tags:
      application: ${spring.application.name}