spring:

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sos
    password:

  jpa:
    hibernate.dialect: org.hibernate.dialect.MariaDBDialect
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create
    properties:
      hibernate:
        # Print all SQL queries from Hibernate execution to console
        show_sql: true
        # Format JPA queries on console with readability
        format_sql: true
        # Print extra information besides SQL queries for debugging
        use_sql_comments: true
      generate-ddl: true

# jwt secret 추후 추가 필요
