spring:
  profiles:
    active: dev

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sos
    password:

  jpa:
    hibernate.dialect: org.hibernate.dialect.MariaDBDialect
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create
    properties:
      hibernate:
        # Print all SQL queries from Hibernate execution to console
        show_sql: true
        # Format JPA queries on console with readability
        format_sql: true
        # Print extra information besides SQL queries for debugging
        use_sql_comments: true
      generate-ddl: true

# jwt secret 임시값 사용
jwt:
  header: Authorization
  # HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  secret: ${jwt-secret}
  token-validity-in-seconds: 86400

cloud:
  aws:
    credentials:
      instance-profile: true # AWS CLI에서 aws configure list 정보를 반영할건지 여부
      access-key: ${aws-s3-access-key}
      secret-key: ${aws-s3-secret-key}
    s3:
      bucket: ${aws-s3-bucket}
    region:
      static: ${aws-region}
    stack:
      auto: false # aws 배포할때 기본으로 CloudFormation 구성을 시작해서 기능을 끔