spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${aws-aurora-endpoint}
    username: ${aws-aurora-username}
    password: ${aws-aurora-password}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # Print all SQL queries from Hibernate execution to console
        show_sql: false
        # Format JPA queries on console with readability
        format_sql: true
        # Print extra information besides SQL queries for debugging
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
      generate-ddl: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
  application:
    name: so1s-api-server

  servlet:
    multipart:
      max-file-size: 30GB
      max-request-size: 30GB


logging:
  level:
    org:
      springframework:
        web:
          filter: DEBUG
      hibernate:
        SQL=DEBUG:

# jwt secret 임시값 사용
jwt:
  header: Authorization
  # HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  secret: ${jwt-secret}
  token-validity-in-seconds: 86400

cloud:
  aws:
    credentials:
      instance-profile: true # AWS CLI에서 aws configure list 정보를 반영할건지 여부
      access-key: ${aws-s3-access-key}
      secret-key: ${aws-s3-secret-key}
    s3:
      bucket: ${aws-s3-bucket}
    region:
      static: ${aws-region}
    stack:
      auto: false # aws 배포할때 기본으로 CloudFormation 구성을 시작해서 기능을 끔

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    tags:
      application: ${spring.application.name}    # 서비스 단위의 식별자. Prometheus label에 추가됨.