INSERT INTO DEPLOYMENT_STRATEGY (name) VALUES ('rolling');
INSERT INTO DEPLOYMENT_STRATEGY (name) VALUES ('static');

INSERT INTO LIBRARY (name) VALUES ('tensorflow');
INSERT INTO LIBRARY (name) VALUES ('pytorch');
INSERT INTO LIBRARY (name) VALUES ('sklearn');
INSERT INTO LIBRARY (name) VALUES ('keras');
INSERT INTO LIBRARY (name) VALUES ('detectron2');
INSERT INTO LIBRARY (name) VALUES ('transformers');
INSERT INTO LIBRARY (name) VALUES ('pytorch_lightning');
INSERT INTO LIBRARY (name) VALUES ('xgboost');


INSERT INTO DATA_TYPE (NAME) VALUES ('numpy');
INSERT INTO DATA_TYPE (NAME) VALUES ('json');
INSERT INTO DATA_TYPE (NAME) VALUES ('text');
INSERT INTO DATA_TYPE (NAME) VALUES ('file');
INSERT INTO DATA_TYPE (NAME) VALUES ('multipart');
INSERT INTO DATA_TYPE (NAME) VALUES ('image');
INSERT INTO DATA_TYPE (NAME) VALUES ('dataframe');
INSERT INTO DATA_TYPE (NAME) VALUES ('series');
