name: Build Image
on:
  push:
    branches:
      - SO1S-137-ci-파이프라인-구축을-통한-pr-테스트-검증-자동화
  pull_request:

jobs:
  gradle-test:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install Sdkman
        run: curl -s "https://get.sdkman.io" | bash
      - name: Set up JDK 11
        run: sdk install java 11.0.15-open
      - name: Setup Gradle
        run: sdk install gradle 7.4.2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Install gradle wrapper
        run: gradle wrapper
      - name: Run build
        run: |
          ./gradlew build
      - name: Run test
        run: |
          ./gradlew test