name: Build Image
on:
  push:
    branches:
      - SO1S-137-ci-파이프라인-구축을-통한-pr-테스트-검증-자동화
  pull_request:

jobs:
  gradle-test:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        run: apt update -y && apt install openjdk-11-jdk -y
      - name: Setup Gradle
        run: apt update -y && apt install gradle -y
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Install gradle wrapper
        run: gradle wrapper
      - name: Run build
        run: |
          ./gradlew build
      - name: Run test
        run: |
          ./gradlew test