name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  jwt-secret: ${{ secrets.JWT_SECRET }}
  aws-s3-access-key: ${{ secrets.AWS_S3_ACCESS_KEY }}
  aws-s3-secret-key: ${{ secrets.AWS_S3_SECRET_KEY }}
  aws-s3-bucket: ${{ secrets.AWS_S3_BUCKET }}
  aws-region: ${{ secrets.AWS_REGION }}

jobs:
  sonarqube-scan:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt update -y && apt install zip unzip -y
          curl -s "https://get.sdkman.io" | bash
          source ~/.sdkman/bin/sdkman-init.sh
          sdk install java 11.0.15.9.1-amzn
          sdk install gradle 7.4.2
          sdk use java 11.0.15.9.1-amzn
          sdk use gradle 7.4.2
          gradle wrapper
          chmod +x gradlew
      - name: Run build
        run: ./gradlew build --stacktrace
        env:
          JAVA_HOME: /root/.sdkman/candidates/java/11.0.15.9.1-amzn
      - name: Run test
        run: ./gradlew test
        env:
          JAVA_HOME: /root/.sdkman/candidates/java/11.0.15.9.1-amzn
      - name: Run jacoco report
        run: ./gradlew jacocoTestReport
        env:
          JAVA_HOME: /root/.sdkman/candidates/java/11.0.15.9.1-amzn
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}\